### ISSUE TITLE
Gives IndexError, any solution?

### ISSUE THREAD

**Issue by charlesbell159** [jure/mathtype_to_mathml#6]
Traceback (most recent call last):
	20: from test.rb:5:in `<main>'
	19: from test.rb:5:in `new'
	18: from /var/lib/gems/2.5.0/gems/mathtype_to_mathml-0.0.7/lib/mathtype_to_mathml.rb:13:in `initialize'
	17: from /var/lib/gems/2.5.0/gems/mathtype_to_mathml-0.0.7/lib/mathtype_to_mathml.rb:13:in `new'
	16: from /var/lib/gems/2.5.0/gems/mathtype-0.0.8/lib/mathtype.rb:15:in `initialize'
	15: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/base.rb:21:in `read'
	14: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/base.rb:145:in `read'
	13: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/base.rb:254:in `start_read'
	12: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/base.rb:147:in `block in read'
	11: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/struct.rb:139:in `do_read'
	10: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/struct.rb:139:in `each'
	 9: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/struct.rb:139:in `block in do_read'
	 8: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/array.rb:295:in `do_read'
	 7: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/array.rb:295:in `loop'
	 6: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/array.rb:297:in `block in do_read'
	 5: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/struct.rb:139:in `do_read'
	 4: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/struct.rb:139:in `each'
	 3: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/struct.rb:139:in `block in do_read'
	 2: from (eval):2:in `do_read'
	 1: from /var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/choice.rb:109:in `current_choice'
/var/lib/gems/2.5.0/gems/bindata-2.4.4/lib/bindata/choice.rb:115:in `instantiate_choice': selection '-77' does not exist in :choices for obj.equation[1].payload (IndexError)

**Comment by jure** [comment]
Hi @charlesbell159! Thanks for reporting this issue!

Does this happen on all equations? Could you provide the `oleObject.bin` which fails?

**Comment by charlesbell159** [comment]
@jure Sorry for late reply, I was busy with something.
Here's oleObject file: 
[oleObject1.zip](https://github.com/jure/mathtype_to_mathml/files/3639664/oleObject1.zip)


and following is the code that I am trying

    require 'mathtype_to_mathml'  
    mathml = MathTypeToMathML::Converter.new("./oleObject1.bin").convert

**Comment by charlesbell159** [comment]
@jure Any progress on this?
